### ISSUE TITLE
Tocar os videos

### ISSUE THREAD

**Issue by antonyalkmim** [kikobr/UXVIDEOS#2]
Seria interessante se realmente tocasse os videos, talvez dê pra embbedar os videos do youtube.

**Comment by kikobr** [comment]
Concordo! Fiz uma prova de conceito um tempo atrás de transformar essa página estática em um gerador de páginas estáticas (tipo o jekly, eleventy, etc). Aí pra cada entrada de um novo vídeo na home, poderíamos ter de fato uma página só pro vídeo e embedar o player lá. O grande benefício do gerador de página estática é que deixaria muito fácil pra qualquer designer colaborar, mesmo que não manje de código. Seria só criar um pull request criando um arquivo markdown, com título, link e alguma tag, sem precisar mexer com o HTML/CSS

**Comment by kikobr** [comment]
@antonyalkmim atualizei o projeto com a opção de assistir os vídeos. o gerador de site estático permite criar um arquivo markdown bem simples e já adicionar automaticamente na home e criar a página do vídeo. fique à vontade para sugerir outros vídeos :)
